### ISSUE TITLE
Patrols breaking during server uptime?

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#967] opened 2022-10-06 14:48 UTC
Okay, I was checking the patrols in Ironforge you did fix and I noticed this Saarz guy walking through the air across the lava through terrain and stuff.

![WoWScrnShot_100622_163522](https://user-images.githubusercontent.com/66841484/194344217-4d5e06ac-7008-47fa-bb52-60b418e5f70b.jpg)

Now I am not sure why or how, but I followed him a few more laps and he didn't do it again, I tried restarting server and he still didn't do it for a few more laps. But I swear it happened, something seems to break patrols periodically or from server being turned on for a period of time maybe? I'm not entirely sure.

HOWEVER, I did notice that just like other patrols, the one you fixed change speed and stuff, change direction they're walking back and  forth.

https://user-images.githubusercontent.com/66841484/194344787-2abca4bd-3999-4991-be94-6893f922171e.mp4

**Comment by UltraNix** [comment] 2022-10-06 20:37
Duplicate of #966.
About the problem with patrols breaking during server uptime - I belive it's not possible. But please, observe it if you can and report again.

**Comment by UltraNix** [comment] 2022-10-24 16:49
Not a generic problem - it's a problem with wrong spawn positions.

**Closed** 2022-10-24 16:58 UTC
Labels: NPC, Waypoints, Movement

**Comment by WarlordXecc** [comment] 2022-10-24 17:07
> Not a generic problem - it's a problem with wrong spawn positions.

Well idk. I've noticed many issues all around with patrols being bugged when you first enter the area.
Like this guy posted below, when I first teleport to Orgrimmar he won't be pushing his cart around. But if I then run outside his viewable radius and run back towards it then the cart fixes himself.


https://user-images.githubusercontent.com/66841484/197584440-0fb802ab-c09c-4950-a656-9fa0396b131f.mp4


https://user-images.githubusercontent.com/66841484/197584448-c2ab6870-1389-48ec-9668-45f98aec1dfe.mp4

**Comment by WarlordXecc** [comment] 2022-10-24 17:08
Had the same issue with this patrol walking straight through these stairs instead of on top of them. Couldn't replicate it now tho for some reason. But I've seen it a few times him walking through the terrain in his patrol.


https://user-images.githubusercontent.com/66841484/197584782-9b8bd333-2c94-4d23-887c-f2286f522d07.mp4

**Comment by UltraNix** [comment] 2022-10-24 17:25
> > Not a generic problem - it's a problem with wrong spawn positions.
> 
> Well idk. I've noticed many issues all around with patrols being bugged when you first enter the area. Like this guy posted below, when I first teleport to Orgrimmar he won't be pushing his cart around. But if I then run outside his viewable radius and run back towards it then the cart fixes himself.
> 
>  2022-10-24.19-01-14.mp4 
>  2022-10-24.19-02-05.mp4

This one is vehicle so not a problem with pathing.

**Comment by UltraNix** [comment] 2022-10-24 17:28
> Had the same issue with this patrol walking straight through these stairs instead of on top of them. Couldn't replicate it now tho for some reason. But I've seen it a few times him walking through the terrain in his patrol.
> 
>  2022-10-24.18-43-15.mp4

This one report.

**Comment by WarlordXecc** [comment] 2022-10-24 17:43
> > > Not a generic problem - it's a problem with wrong spawn positions.
> > 
> > 
> > Well idk. I've noticed many issues all around with patrols being bugged when you first enter the area. Like this guy posted below, when I first teleport to Orgrimmar he won't be pushing his cart around. But if I then run outside his viewable radius and run back towards it then the cart fixes himself.
> > 2022-10-24.19-01-14.mp4
> > 2022-10-24.19-02-05.mp4
> 
> This one is vehicle so not a problem with pathing. But I cannot reproduce it on my local.

Yeah I can't perfectly replicate it either. But I've had it happen multiple times, fixes itself when you leave area and come back tho.



> > Had the same issue with this patrol walking straight through these stairs instead of on top of them. Couldn't replicate it now tho for some reason. But I've seen it a few times him walking through the terrain in his patrol.
> > 2022-10-24.18-43-15.mp4
> 
> This one report.

Report what? It's the same bug that's happened with the rest of reports in this issue on Sraaz and guy in Hearthglen. Sometimes when I first arrive the patrol is fucked. And when I stick around it never happens again, I don't even know how to replicate it, it just happens sometimes.

**Comment by UltraNix** [comment] 2022-10-24 17:46
`Had the same issue with this patrol walking straight through these stairs instead of on top of them. Couldn't replicate it now tho for some reason. But I've seen it a few times him walking through the terrain in his patrol.
2022-10-24.18-43-15.mp4

This one report.`

As I can see on local server it happens every time. Wrong waypoint path.

**Comment by WarlordXecc** [comment] 2022-10-24 17:54
You mean like this below the stairs so you can't even see him?
I know he always is slightly below the terrain with his path inside the Stormwind Keep, but on rare occasions I see him walk below the terrain to the point you can't see him at all without nameplates.

![WoWScrnShot_102422_195106](https://user-images.githubusercontent.com/66841484/197593156-f7f89e1b-a0a1-40d0-b580-79ab156fca20.jpg)

**Comment by UltraNix** [comment] 2022-10-24 17:57
Yes. This one NPC have wrong path points, that's why he lands under terrain for a second.
